In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import os

In [2]:
os.getcwd()

'/home/dermodkkelly/rumen_microbiome_pipeline'

In [3]:
os.chdir("/home/dermodkkelly/rumen_microbiome_pipeline")

In [4]:
FEATURE_FILE = "results/rumen_combined_feature-table.tsv"
TAX_FILE = "results/rumen_combined_exported-taxonomy.tsv"

OUTDIR = Path("postprocessing/output")
OUTDIR.mkdir(parents=True, exist_ok=True)

In [5]:
tax = pd.read_csv(TAX_FILE, sep="\t")
tax.head()

,Feature ID,Taxon,Confidence
0,0000b84a296311cfe214483f9e2bfe28,d__Bacteria; p__Firmicutes; c__Clostridia; o__...,0.838961
1,000135ece78204cf880cf0c64a4f6cb7,d__Bacteria; p__Firmicutes; c__Clostridia; o__...,0.937315
2,0001a1fb4083eb04593b5d4e110c31ba,d__Bacteria; p__Bacteroidota; c__Bacteroidia,0.986549
3,0001fb18436a5c8e4c11d91e9aa3c6e9,d__Bacteria; p__Actinobacteriota; c__Coriobact...,0.988822
4,00021929c0a6e082fd353a3d9fef8e51,d__Bacteria; p__Firmicutes; c__Clostridia; o__...,0.960691

In [6]:
def parse_taxonomy(t):
    ranks = {"Kingdom":"Unassigned","Phylum":"Unassigned","Class":"Unassigned",
             "Order":"Unassigned","Family":"Unassigned","Genus":"Unassigned","Species":"Unassigned"}

    if pd.isna(t):
        return pd.Series(ranks)

    parts = [x.strip() for x in str(t).split(";")]

    rank_map = {
        "d__":"Kingdom",
        "p__":"Phylum",
        "c__":"Class",
        "o__":"Order",
        "f__":"Family",
        "g__":"Genus",
        "s__":"Species"
    }

    for p in parts:
        for prefix, rank in rank_map.items():
            if p.startswith(prefix):
                val = p.replace(prefix, "").strip()
                if val == "":
                    val = "Unassigned"
                ranks[rank] = val

    return pd.Series(ranks)

parsed = tax["Taxon"].apply(parse_taxonomy)
tax = pd.concat([tax, parsed], axis=1)

tax.head()

,Feature ID,Taxon,Confidence,Kingdom,Phylum,Class,Order,Family,Genus,Species
0,0000b84a296311cfe214483f9e2bfe28,d__Bacteria; p__Firmicutes; c__Clostridia; o__...,0.838961,Bacteria,Firmicutes,Clostridia,Christensenellales,Christensenellaceae,Christensenellaceae_R-7_group,uncultured_rumen
1,000135ece78204cf880cf0c64a4f6cb7,d__Bacteria; p__Firmicutes; c__Clostridia; o__...,0.937315,Bacteria,Firmicutes,Clostridia,Christensenellales,Christensenellaceae,Christensenellaceae_R-7_group,Unassigned
2,0001a1fb4083eb04593b5d4e110c31ba,d__Bacteria; p__Bacteroidota; c__Bacteroidia,0.986549,Bacteria,Bacteroidota,Bacteroidia,Unassigned,Unassigned,Unassigned,Unassigned
3,0001fb18436a5c8e4c11d91e9aa3c6e9,d__Bacteria; p__Actinobacteriota; c__Coriobact...,0.988822,Bacteria,Actinobacteriota,Coriobacteriia,Coriobacteriales,Unassigned,Unassigned,Unassigned
4,00021929c0a6e082fd353a3d9fef8e51,d__Bacteria; p__Firmicutes; c__Clostridia; o__...,0.960691,Bacteria,Firmicutes,Clostridia,Peptostreptococcales-Tissierellales,Anaerovoracaceae,Family_XIII_AD3011_group,Unassigned

In [7]:
for rank in ["Phylum","Class","Order","Family","Genus","Species"]:
    assigned = (tax[rank] != "Unassigned").sum()
    pct = assigned / len(tax) * 100
    print(rank, assigned, round(pct,1))

Phylum 83164 91.3
Class 82394 90.4
Order 80340 88.2
Family 78698 86.4
Genus 70647 77.5
Species 48526 53.2

In [8]:
feat = pd.read_csv(
    FEATURE_FILE,
    sep="\t",
    skiprows=1
)

feat.rename(columns={feat.columns[0]: "FeatureID"}, inplace=True)
feat.head()

,FeatureID,EN00011682__21,EN00011682__ControlP_ive_8,EN00011682__Minus14,EN00011682__Plus5,EN00011682__Sheep_CT24_295,EN00011682__Sheep_CT24_296,EN00011682__Sheep_CT24_297,EN00011682__Sheep_CT24_298,EN00011682__Sheep_CT24_299,...,Tully__91292_S99,Tully__91483_S103,Tully__91756_S39,Tully__92322_S20,Tully__n-13-8_S81,Tully__n-16-7_S82,Tully__n-23-7_S100,Tully__N-27-7_S49,Tully__NEG-7-10_S95,Tully__Zymo-2_S87
0,0000b84a296311cfe214483f9e2bfe28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,000135ece78204cf880cf0c64a4f6cb7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0001a1fb4083eb04593b5d4e110c31ba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0001fb18436a5c8e4c11d91e9aa3c6e9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,00021929c0a6e082fd353a3d9fef8e51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
feat = feat.set_index("FeatureID")

sample_matrix = feat.T
sample_matrix.index.name = "SampleID"
sample_matrix.reset_index(inplace=True)

sample_matrix.head()

FeatureID,SampleID,0000b84a296311cfe214483f9e2bfe28,000135ece78204cf880cf0c64a4f6cb7,0001a1fb4083eb04593b5d4e110c31ba,0001fb18436a5c8e4c11d91e9aa3c6e9,00021929c0a6e082fd353a3d9fef8e51,00025030599fa2848af2711196b72760,00034ec4df8628c90b5669ba90db0def,000407eb2b7635995cd64f936d5753d1,00040bd2e1f507e209fb0a153a6ca3a0,...,fff9feea247cb2ff1b24576006e1f44b,fffccadc8fcf99b306bd54d18c203d0c,fffd1275c99241770dbdecb31991d3dd,fffd3a11c88e827f4377bca16665f989,fffdaf7af517e4e6fcae31b6c54091ae,fffdc059674592831636fd03baa29eed,fffe1366203f43d251526329507be2d1,fffeda2f54ff42633e5926721bc88de8,ffff5b76e7c8c74f71dfb6b6da89c7a6,ffffa5fc5e60f992857e2d63814d3452
0,EN00011682__21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,EN00011682__ControlP_ive_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,EN00011682__Minus14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,EN00011682__Plus5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,EN00011682__Sheep_CT24_295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
# ---- genus lookup ----
lookup = tax[["Feature ID","Genus"]].copy()
lookup.columns = ["FeatureID","Genus"]
lookup["Genus"] = lookup["Genus"].replace("", "Unassigned")

# ---- collapse ASVs to genus (fast column-grouping, no giant melt) ----
# feat is features x samples, indexed by FeatureID
feat_genus = feat.copy()
feat_genus.index = feat_genus.index.map(
    lookup.set_index("FeatureID")["Genus"]
).fillna("Unassigned")

genus_by_sample = feat_genus.groupby(level=0).sum()      # rows = genus, cols = samples
genus_wide = genus_by_sample.T.reset_index().rename(columns={"index": "SampleID"})

genus_wide.head()

FeatureID,SampleID,0319-6G20,0319-7L14,11-24,1174-901-12,67-14,A4b,ADurb.Bin063-1,ASF356,Abditibacterium,...,mle1-7,p-1088-a5_gut_group,p-251-o5,p-2534-18B5_gut_group,possible_genus_Sk018,probable_genus_10,uncultured,vadinBA26,vadinBE97,vadinHA49
0,EN00011682__21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,24.0,16.0,0.0,0.0,26.0,624.0,0.0,6.0,0.0
1,EN00011682__ControlP_ive_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,EN00011682__Minus14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,12.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0
3,EN00011682__Plus5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,EN00011682__Sheep_CT24_295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,58.0,17.0,0.0,0.0,0.0,641.0,0.0,6.0,0.0

In [11]:
print(genus_wide.shape)          
print(genus_wide["SampleID"].nunique())   # expect 1969, all unique
# genus matrix row sums should equal the original per-sample depth
genus_wide.set_index("SampleID").sum(axis=1).describe()

(1969, 926)
1969

count      1969.000000
mean      49891.888776
std       20643.329780
min           0.000000
25%       36545.000000
50%       43822.000000
75%       61009.000000
max      164896.000000
dtype: float64

In [12]:
# what are the lowest-depth samples?
depths = genus_wide.set_index("SampleID").sum(axis=1).sort_values()
depths.head(15)

SampleID
Tully__60424_S64        0.0
Tully__61385_S74        4.0
Tully__N-18-8_S108      7.0
Tully__20328_S15       10.0
Tully__72295_S45       10.0
Tully__N-6-8_S113      13.0
Tully__n-23-7_S100     15.0
Tully__n-16-7_S82      25.0
Tully__H2O-26-8_S35    31.0
EN00011689__Minus17    33.0
Tully__60498_S65       35.0
Tully__n-13-8_S81      38.0
Tully__NEG-7-10_S95    42.0
Tully__80322_S37       50.0
Tully__N-27-7_S49      51.0
dtype: float64

In [13]:
print("samples < 1000 reads:", (depths < 1000).sum())
print("samples < 5000 reads:", (depths < 5000).sum())

samples < 1000 reads: 23
samples < 5000 reads: 32

In [14]:
import re

# corrected: allow optional underscore before trailing number (handles ControlP_ive_5)
control_pattern = r'__(?:ControlN_ive|ControlNive|ControlP_ive|Minus|Plus|N|P)_?\d*$'
is_control = genus_wide["SampleID"].str.contains(control_pattern, regex=True)

# The three full Tully (beef) MiSeq runs carry their own controls, named
# differently: 16S standards/clones (16S1, 16S-Clone-A), Zymo mock
# communities (Zymo-2, Zymo1, Zymo-1-0), extraction/PCR negatives (N-27-7,
# n-13-8, NEG-7-10, N-14-8-PCR-N), a water blank (H2O-26-8) and a saliva
# sample. Animal stems there are numeric short tags, so none can match.
tully_control_pattern = r'^Tully__(?:16S|Zymo|N-|n-|NEG|H2O|saliva)'
is_tully_control = genus_wide["SampleID"].str.contains(tully_control_pattern, regex=True)
print("Tully controls:", is_tully_control.sum())          # expect 22
is_control = is_control | is_tully_control

print("Flagged as control/blank:", is_control.sum())      # expect 50 (28 + 22 Tully)
print(sorted(genus_wide.loc[is_control, "SampleID"].tolist()))

Tully controls: 22
Flagged as control/blank: 50
['EN00010710__N1', 'EN00010710__N2', 'EN00010710__N3', 'EN00010710__N4', 'EN00010710__N5', 'EN00010710__P1', 'EN00011679__ControlN_ive_6', 'EN00011679__ControlP_ive_5', 'EN00011679__Minus1', 'EN00011679__Plus1', 'EN00011681__ControlNive_8', 'EN00011681__Minus5', 'EN00011681__Plus4', 'EN00011682__ControlP_ive_8', 'EN00011682__Minus14', 'EN00011682__Plus5', 'EN00011684__ControlP_ive_9', 'EN00011684__Minus16', 'EN00011684__Plus14', 'EN00011685__ControlP_ive_4', 'EN00011685__Minus16', 'EN00011685__Plus16', 'EN00011686__Minus19', 'EN00011686__Plus19', 'EN00011687__ControlN_ive_5', 'EN00011687__ControlP_ive_10', 'EN00011689__Minus17', 'EN00011689__Plus17', 'Tully__16S-Clone-A_S50', 'Tully__16S-Clone-b_S5', 'Tully__16S-clone-c_S109', 'Tully__16S1_S93', 'Tully__16S2_S74', 'Tully__16S3_S110', 'Tully__H2O-26-8_S35', 'Tully__N-14-8-PCR-N_S68', 'Tully__N-18-8_S108', 'Tully__N-27-7_S49', 'Tully__N-4-8-2020_S9', 'Tully__N-6-8_S113', 'Tully__N-8-7-EXTRACTION_S59', 'Tully__NEG-7-10_S95', 'Tully__Zymo-1-0_S114', 'Tully__Zymo-2_S87', 'Tully__Zymo1_S2', 'Tully__Zymo3_S3', 'Tully__n-13-8_S81', 'Tully__n-16-7_S82', 'Tully__n-23-7_S100', 'Tully__saliva_S92']

In [15]:
# Save corrected genus-level count tables
genus_wide.to_csv(
    OUTDIR / "genus_counts_with_controls_515F_806R.csv",
    index=False
)

genus_bio = genus_wide[~is_control].reset_index(drop=True)

genus_bio.to_csv(
    OUTDIR / "genus_counts_no_controls_515F_806R.csv",
    index=False
)

print(f"with_controls: {genus_wide.shape[0]}")   # expect 1969
print(f"no_controls:   {genus_bio.shape[0]}")    # expect 1919

# Save corrected taxonomy lookup
tax.to_csv(
    OUTDIR / "taxonomy_lookup_515F_806R.csv",
    index=False
)

with_controls: 1969
no_controls:   1919